name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/mybeeCompany  # Adjust this path
          sudo git pull origin master
          sudo composer update
          sudo composer install
          sudo php artisan migrate --force
          sudo php artisan tenants:migrate
          sudo php artisan config:cache
          sudo php artisan route:cache
          sudo php artisan view:cache
          sudo systemctl restart apache2 
        EOF
