name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/mybeeCompany  # Adjust this path
          git pull origin master
          composer update
          composer install --no-dev --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan tenants:migrate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart apache2 
        EOF
